### ISSUE TITLE
[BUG] NullPointerException

### ISSUE THREAD

**Issue by DeflatedPickle** [dheid/colorpicker#26]
I have a colour picker inside a dockable frame from [DockingFrames](https://github.com/Benoker/DockingFrames). It starts off minimized and when it is shown the colour picker throws an NPE
```java
java.lang.NullPointerException
	at java.desktop/javax.swing.plaf.basic.BasicSliderUI.calculateFocusRect(BasicSliderUI.java:674)
	at java.desktop/javax.swing.plaf.basic.BasicSliderUI.calculateGeometry(BasicSliderUI.java:660)
	at com.bric.colorpicker.colorslider.ColorSliderUI.access$000(ColorSliderUI.java:47)
	at com.bric.colorpicker.colorslider.ColorSliderUI$ResizeListener.componentResized(ColorSliderUI.java:207)
	at java.desktop/java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:168)
	at ...
```

**Comment by dheid** [comment]
Hi @DeflatedPickle ! Thanks for submitting this bug. I will analyze the problem.

**Comment by dheid** [comment]
Hey @DeflatedPickle! The component has not been installed properly using the installUI method. I added a fix to prevent the NPE in this case, but I don't think that the Color Slider will be shown as expected now. Could you try it again, please? If the problem still occurs, please provide me some code on how you add the Color Picker to DockingFrames so that I can reproduce the bug.

**Comment by dheid** [comment]
No response. So I assume the bug is resolved.
