### ISSUE TITLE
[BUG] Illegal argument exception when color wheel is tiny

### ISSUE THREAD

**Issue by seedee** [dheid/colorpicker#51]
**Describe the bug**
When the component gets too small such as when the frame is resized, the color wheel disappears entirely. However, the selection handle/circle is still visible and creates an exception when you click on it.

```java
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: The saturation value (-5.3851647) must be between [0,1]
	at com.bric.colorpicker.ColorPickerPanel.setHSB(ColorPickerPanel.java:460)
	at com.bric.colorpicker.ColorPickerPanel$ColorPickerMouseInputListener.mousePressed(ColorPickerPanel.java:682)
```

**Comment by dheid** [comment]
Thanks for opening the issue! I will look at it

**Comment by dheid** [comment]
I think I fixed this error. You'll find a new version 1.4.8 with the bugfix included.
